[env:esp32doit-devkit-v1]
platform  = espressif32
board     = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

board_build.filesystem = littlefs

lib_deps =
  https://github.com/me-no-dev/ESPAsyncWebServer.git
  https://github.com/me-no-dev/AsyncTCP.git
  bblanchon/ArduinoJson @ ^7.0.0
  fastled/FastLED @ 3.5.0
  dfrobot/DFRobotDFPlayerMini @ ^1.0.5
  adafruit/Adafruit SSD1306 @ ^2.5.7
  adafruit/Adafruit GFX Library @ ^1.11.9

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DOLED_SDA=21
  -DOLED_SCL=22
  ; ── ADC1 únicamente (aislado del WiFi) ──
  -DPIN_PAD0=34
  -DPIN_PAD1=35
  -DPIN_PAD2=32
  -DPIN_PAD3=33
  -DPIN_PAD4=36
  -DPIN_PAD5=39
  ; ── LEDs ──
  -DPIN_LEDS=4
  -DNUM_LEDS=60
  ; ── DFPlayer ──
  ; DFPlayer 1 — sonidos de pads (UART1)
  -DPIN_DFP1_RX=16
  -DPIN_DFP1_TX=17
  ; DFPlayer 2 — pista de fondo (UART2)
  -DPIN_DFP2_RX=27
  -DPIN_DFP2_TX=14
  ; ── Juego ──
  -DPIEZO_UMBRAL=300
  -DTIEMPO_REFLEJO_MS=1500